# Generated by Django 4.0.3 on 2022-03-30 19:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to='documents/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
